spring.application.name=${SPRING_APPLICATION_NAME}

server.port=${SERVER_PORT}

spring.config.import=optional:configserver:${CONFIG_SERVER_URL}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

front_end=${FRONT_END}
front_end2=${FRONT_END2}
back_end=${BACK_END}

otp.exp=${OTP_EXP}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB

grok.api-key=${GROQ_API_KEY}
grok.url=${GROQ_URL}
grok.model=${GROQ_MODEL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.default-encoding=UTF-8